name: Run Shell Script on Local Linux Machine

on:
  workflow_dispatch:

jobs:
  run-script:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: Run shell script
        run: ./GithubActions.sh
